apiVersion: v2
name: location-api
description: A Helm chart for Kubernetes
type: application
version: "0.1.0"
appVersion: "0.0.1"
kubeVersion: ">=1.24"

dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 2.13.3
  - name: reloader
    condition: reloader.enabled
    version: "1.0.50"
    repository: "https://stakater.github.io/stakater-charts"
